### ISSUE TITLE
Allow subtasks of a repeated task to use different models

### ISSUE THREAD

**Issue by jonrkarr** [biosimulators/Biosimulators_utils#31]
This is mostly allowed with a couple exceptions
- [ ] Validation of XPath targets of variables of data generators needs to be appropriately handled for instances of `Task`
   - Check that targets are valid with the language of at least one subtask
- [ ] Handle errors in task executer not being able to generate all variables
- [ ] Add test for this to test suite
